services:
  app:
    container_name: app
    build:
      context: ./application
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: shopdb
    ports:
      - 5000:5000
  
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shopdb
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_simulator:
    build: 
      context: ./etl_simulator
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: shopdb
    entrypoint: ["python", "etl_simulator.py"] 

  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: shopdb
    ports:
      - "8081:8080"